spring:
  application:
    name: springboot
  datasource:
    druid:
      name: webapi
      url: jdbc:mysql://localhost:3306/web_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root


server:
  port: 8080    # 端口
  servlet:
    context-path: /api/v1   # 访问根目录

hyatt:
  jwt:
    secret-key:  1a1a75c6c59d1b89792d7ffb8b257fe47aabb103 # 密钥
    expiration-time: 108000000 # 过期时间 毫秒 30*60*60*100
    issuer: hyatt #发行的主体
    subject: 主题 # 主题
    audience: 群众 # 受众人群
